### ISSUE TITLE
Graphics not drawn

### ISSUE THREAD

**Issue by PavelVeselsky** [PavelVeselsky/FlareClusterLayer#1]
With the example data, method `_graphicDraw` never runs. With my data (in S-JTSK, wkid 102067) it runs (though it runs twice for each graphic, I don't know why); clusters, singles and graphics are created with both datasets and seem correct. I'm afraid there is some issue in the hardly debuggable area around this event (method `_setMap`, row 156):

`this.events.push(on(this, "graphic-draw", this._graphicDraw));`

I don't mind how does it run on my site; first I need to make it work in the laboratory, or with the example data. @nickcam, can you look at it? I hope I have corrected all the over-fitting for my machine and that it will work as-is, if not, please report.

**Comment by nickcam** [comment]
Hi Pavel,

I've had a quick look....there's a few things not quite working to get the intial points to show up. `_graphicDraw` is never being called as graphics aren't being drawn due to errors in adding them. Once I got them showing up there were different errors as well though.
Firstly I had to remove the namespacing to get it to run 
`
"cluster/FlareClusterLayer",
`
It may work for you but the constructor wouldn't work if in was in there when I was running it.

In `_clusterData()` I notice you've changed the cluster points to contain the web merc points. 
`
cl.x = cl.clusterCount > 0 ? (web[0] + (cl.x \* cl.clusterCount)) / (cl.clusterCount + 1) : web[0];
cl.y = cl.clusterCount > 0 ? (web[1] + (cl.y \* cl.clusterCount)) / (cl.clusterCount + 1) : web[1];

//push every point into the cluster so we have it for area display if required. This could be omitted if never checking areas, or on demand at least
if (this.clusterAreaDisplay) {
    cl.points.push([web[0], web[1]]);
}
`

To get the clusters to initally show, you'll need to change those back to use the actual point data, ie: `obj.x` `obj.y` instead of `web[0]` `web[1]`.
Alternatively in `_createCluster()` you could set the spatial ref of the cluster points specifically to web merc. ie:
`
attributes.isCluster = true; 
point.spatialReference = new SpatialReference({ wkid: "102100" });
var graphic = new Graphic(point, null, attributes, null);
cluster.graphic = graphic;
cluster.areaGraphic = areaGraphic;
this.add(graphic);
`

Also I had to remove the call to `graphic.setSymbol(this.renderer.getSymbol(graphic));` for them to show. Its not needed for the clusters or the single points as the default renderer will create the symbol for them anyway.
It's only needed for setting a symbol on the area polygon using the clusterAreaRenderer object.

Once I got the clusters to show there were a bunch of other errors when mousing over a cluster. I didn't get into looking at those though. 
Hope it helps.

Thanks,
Nick

**Comment by PavelVeselsky** [comment]
Thank you very much! Currently I work on an unrelated project, but I will return to this ASAP. With your answer, I'm not stuck any longer, and I hope I will handle the other issues starting from this your help. If not, I'll update the code and start another issue to ask.

**Comment by PavelVeselsky** [comment]
Thank you again! I changed it according to your advice and the graphics show, at least in the simplest case (client side + area mode none). There are some more errors, so I'm working on correcting them, but this one is no longer a problem.
